name: Build and Push Docker Image with Auto-Incremented and `latest` Tags

on:
    push:
        branches:
            - "*"

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Get the latest Docker tag
              id: get-latest-tag
              run: |
                  LATEST_TAG=$(curl -s -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" \
                    "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/unity-builder/tags" \
                    | jq -r '.results[].name' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
                  if [ -z "$LATEST_TAG" ]; then
                    LATEST_TAG="v0.0.0"
                  fi
                  echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

            - name: Increment version
              id: increment-tag
              run: |
                  LATEST_TAG=${{ env.LATEST_TAG }}
                  VERSION=${LATEST_TAG#v}
                  MAJOR=$(echo $VERSION | cut -d. -f1)
                  MINOR=$(echo $VERSION | cut -d. -f2)
                  PATCH=$(echo $VERSION | cut -d. -f3)
                  NEW_TAG="v$MAJOR.$MINOR.$((PATCH + 1))"
                  echo "NEW_TAG=${NEW_TAG}" >> $GITHUB_ENV
                  echo "New Docker tag: ${NEW_TAG}"

            - name: Build Docker image with both tags
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/unity-builder:${{ env.NEW_TAG }} \
                               -t ${{ secrets.DOCKER_USERNAME }}/unity-builder:latest .

                  # docker run  --rm bsahbi/unitybuilder java -version
                  # docker run  --rm bsahbi/unitybuilder bash -c "sdkmanager --version"
                  # docker run  --rm bsahbi/unitybuilder gradle --version
                  # docker run  --rm bsahbi/unitybuilder bash -c "gradle --version"

            - name: Push Docker image with version and latest tags
              run: |
                  docker push ${{ secrets.DOCKER_USERNAME }}/unity-builder:${{ env.NEW_TAG }}
                  docker push ${{ secrets.DOCKER_USERNAME }}/unity-builder:latest

